export const COMMAND_PARAMETERS = {
  'c:show': 'string',
  'c:hide': 'string',
  'c:sort': 'string',
  'c:has': 'string',
  'c:resolve': 'string',
  'c:case': 'string',
  'c:limit': 'integer',
  'c:limitPerDB': 'integer',
  'c:start': 'integer',
  'c:includeNull': 'boolean',
  'c:lang': 'string',
  'c:join': 'string',
  'c:tree': 'string',
  'c:timing': 'boolean',
  'c:exactMatchFirst': 'boolean',
  'c:distinct': 'string',
  'c:retry': 'boolean',
};

export const EVENT_TYPES = [
  'BATTLE_RANK',
  'BATTLERANKUP',
  'BATTLERANKUPS',
  'ITEM',
  'ITEMADDED',
  'ACHIEVEMENT',
  'ACHIEVEMENTEARNED',
  'DEATH',
  'DEATHS',
  'KILL',
  'KILLS',
  'VEHICLE_DESTROY',
  'FACILITY_CHARACTER',
  'PLAYERFACILITY',
  'FACILITYPLAYER',
  'CHARACTERFACILITY',
  'FACILITYCHARACTER'
];